import ProjectDescription
import DependencyPlugin

let workspace = Workspace(
    name: Project.Environment.appName,
    projects: [
        "Projects/*"
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .relevant
        )
    )
)
